# Generated by Django 4.2.4 on 2024-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genter',
            field=models.CharField(default='Men', max_length=200),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
