# Generated by Django 4.2.4 on 2024-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_genter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genter',
            field=models.CharField(default='men', max_length=200),
        ),
    ]
